4.0

Traceback (most recent call last):
  File "ex_inverse.py", line 6, in <module>
    b=f(0)
  File "ex_inverse.py", line 2, in f
    return 1/x
ZeroDivisionError: division by zero
